### PR TITLE
[jsk_tools] Add speak warnings node

### PR DESCRIPTION
**Pull request by 708yamaguchi**
Cherry pick https://github.com/jsk-ros-pkg/jsk_common/pull/1607
https://github.com/jsk-ros-pkg/jsk_common/pull/1607

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
I use this node in fetch.

It works!

**Comment by 708yamaguchi** [comment]
cc @iory

**Comment by 708yamaguchi** [comment]
@iory

Could you review this?

**Comment by iory** [comment]
Please close this PR.
This PR merged #6

**Pull request closed without merging**
