### PR TITLE
Poke when subscribed with fetch15

### PR DESCRIPTION
**Pull request by iory**
https://github.com/jsk-ros-pkg/jsk_common/pull/1735

# What is this?

If the diagnostics nodelet is currently subscribed,but the publish function is not executed (`vital_checker->poke()` is not executed), it publishes diagnostics with an error level.
This publishes error level diagnostics only at the beginning because poke is not called when subscribing starts.

This is to change to output diagnostics at the OK level by inserting a poke when switching from the not subscribed state to the subscribed state.

close #8

### CODE REVIEW

**Comment by iory** [comment]
@708yamaguchi
Could you review this?

**Comment by 708yamaguchi** [comment]
OK, I will check next Monday.

**Comment by iory** [comment]
Thank you!

**Comment by 708yamaguchi** [comment]
This PR, https://github.com/jsk-ros-pkg/jsk_recognition/pull/2690 and https://github.com/jsk-ros-pkg/jsk_recognition/pull/2691 fix `dual_fisheye_to_panorama`'s error diagnostics at the start of the subscribe.

But fetch still speaks
```
[INFO] [1653883367.255447] [/audible_warning:rosout]: audible warning error name "/Sensors/Head Camera/head_camera head_camera_nodelet_manager:  head_camera depth_registered relay_image_compressed::Relay"
[INFO] [1653883367.258379] [/audible_warning:rosout]: audible warning talking: error. Sensors Head Camera head camera head camera nodelet manager:  head camera depth registered relay image compressed::Relay subscribed but no input. Is  head camera depth registered hw registered image rect compressedDepth active?
```

We may need to change image_transport `png_level` ?

**Comment by iory** [comment]
> But fetch still speaks

That's another problem. This solves the problem that a diagnostics error is absolutely output if you haven't subscribed to relay for a while.

> We may need to change image_transport png_level ?

If the relay input is not coming out, I think that this error will occur because the original diagnostics function works well.
So, please change `png_level`.

**Comment by 708yamaguchi** [comment]
Thank you.

I did
- reduce `png_level`
- reduce CPU usage

Then, this problem is solved.

**Review by 708yamaguchi — APPROVED** [review]

**Pull request merged**
